### ISSUE TITLE
Thank you for the "LIKE" feature. Hope to see "OR" and varbinary / varchar to complement the LIKE in the next release!

### ISSUE THREAD

**Issue by sprappcom** [crossdb-org/crossdb#23]
thank you so much.

1. "OR" syntax is needed.
2. varchar/varbinary will make this really "production ok". 

will be one of the first to contribute findings on usage.

**Comment by jcwangxp** [comment]
OR is supported, please try
a=xx and b=xx OR c=xx and d=xx OR e=xx
if all OR clauses can use index, then will go index else scan table
you can use explain to see the index list.

**Comment by kolinfluence** [comment]
varchar / varbinary pls! thx!

**Comment by jcwangxp** [comment]
varchar is complex feature, need more time to dev.

**Comment by kolinfluence** [comment]
@jcwangxp yes i understand.

can you please please provide a reasonable ETA for the expectation of functions?
i've seen a lot of repos that say these and that are supported but in the end the ETA can be 6 mths to 1.5 years and still waiting.

possible to provide a reasonable expected ETA for this varchar? because it's really a very important feature for "production-ok" use.

for production ready need wal... 

then replication i guess

hope to see some ETAs on roadmap. 
thx

**Comment by jcwangxp** [comment]
will deliver varchar initial version this weekend, then you can have a test.
wal is ok, replication is future plan, I'd like to finish most embedded db features first, then client-server, then replication.

**Comment by jcwangxp** [comment]
I've delivered the VARCHAR, you can have a test.

**Comment by jcwangxp** [comment]
BINARY and VARBINARY are supported.
https://crossdb.org/sql/data-types/
